apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.mainReleaseName }}-httproute
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
    sectionName: web
  rules:
  # {{ .Values.path }} pathprefix
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.path }}
    backendRefs:
    - name: {{ .Values.mainReleaseName }}-express
      namespace: elasticdt
      port: 8081

