apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mainReleaseName }}-pv
  labels:
    app: {{ .Values.mainReleaseName }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: {{ .Values.persistence.hostPath }}
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mainReleaseName }}-pvc
  labels:
    app: {{ .Values.mainReleaseName }}
spec:
  volumeName: {{ .Values.mainReleaseName }}-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
