# Enable the Gateway provider but disable the default Ingress provider
providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

# Allow the Gateway to expose HTTPRoute from all namespaces
gateway:
  listeners:
    web:
      namespacePolicy: All
    # neo4j:
    #   port: 7474
    #   protocol: HTTP
    #   namespacePolicy: All
    # bolt:
    #   port: 7867
    #   protocol: HTTP
    #   namespacePolicy: All

# Enable the dashboard
ingressRoute:
  dashboard:
    enabled: true

# Expose the service as a NodePort type on ports 30080 and 30443.
# Expose the dashboard on port 39000. 
service:
  type: NodePort
ports:
  web:
    nodePort: 30080
  websecure:
    nodePort: 30443
  traefik:
    expose:
      default: true
  # neo4j:
  #   # neo4j uses port 7474 for http
  #   port: 7474
  #   exposedPort: 7474
  #   expose:
  #     default: true
  # bolt:
  #   # neo4j uses port 7687 for bolt
  #   port: 7867
  #   exposedPort: 7687
  #   expose:
  #     default: true
