apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.mainReleaseName }}-httproute
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
    sectionName: web
  rules:
  # {{ .Values.path }} pathprefix
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.path }}
    backendRefs:
    - name: {{ .Values.mainReleaseName }}-phpmyadmin
      namespace: elasticdt
      port: 80
    filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: {{ .Values.mainReleaseName }}-stripprefix

---

# Strip {{ .Values.path }} prefix before forwarding requests to whoami
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.mainReleaseName }}-stripprefix
  namespace: elasticdt
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.path }}
